// src/components/photos/Lightbox.tsx
import React, { useEffect, useRef, useState } from 'react';

interface LightboxProps {
  imageSrc: string;
  onClose: () => void;
}

const Lightbox: React.FC<LightboxProps> = ({ imageSrc, onClose }) => {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  const stateRef = useRef({
    img: null as HTMLImageElement | null,
    scale: 1,
    baseScale: 1,
    cx: 0,
    cy: 0,
    isDragging: false,
    dragStartX: 0,
    dragStartY: 0,
    dragStartCx: 0,
    dragStartCy: 0,
    hasDragged: false,
    lastPinchDist: 0,
    lastTapTime: 0,
  });

  const draw = () => {
    const canvas = canvasRef.current;
    const ctx = canvas?.getContext('2d');
    const s = stateRef.current;
    if (!canvas || !ctx || !s.img) return;

    ctx.clearRect(0, 0, canvas.width, canvas.height);
    const w = s.img.naturalWidth * s.scale;
    const h = s.img.naturalHeight * s.scale;
    ctx.drawImage(s.img, s.cx - w / 2, s.cy - h / 2, w, h);
  };

  const resetView = () => {
    const canvas = canvasRef.current;
    const s = stateRef.current;
    if (!canvas || !s.img) return;

    const padding = 0.9;
    const scaleX = canvas.width / s.img.naturalWidth;
    const scaleY = canvas.height / s.img.naturalHeight;
    s.baseScale = Math.min(scaleX, scaleY) * padding;
    s.scale = s.baseScale;
    s.cx = canvas.width / 2;
    s.cy = canvas.height / 2;
  };

  // Lock body scroll
  useEffect(() => {
    const prev = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    return () => {
      document.body.style.overflow = prev;
    };
  }, []);

  // Escape key to close
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [onClose]);

  // Load image and setup canvas
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const dpr = window.devicePixelRatio || 1;

    const resize = () => {
      canvas.width = window.innerWidth * dpr;
      canvas.height = window.innerHeight * dpr;
      canvas.style.width = window.innerWidth + 'px';
      canvas.style.height = window.innerHeight + 'px';
      if (stateRef.current.img) {
        resetView();
        draw();
      }
    };

    const img = new Image();
    img.onload = () => {
      stateRef.current.img = img;
      setLoading(false);
      resize();
      draw();
    };
    img.onerror = () => {
      setLoading(false);
      setError(true);
    };
    img.src = imageSrc;

    window.addEventListener('resize', resize);
    resize();

    return () => window.removeEventListener('resize', resize);
  }, [imageSrc]);

  // Wheel zoom
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const handler = (e: WheelEvent) => {
      e.preventDefault();
      const s = stateRef.current;
      if (!s.img) return;

      const dpr = window.devicePixelRatio || 1;
      const factor = e.deltaY < 0 ? 1.1 : 1 / 1.1;
      const newScale = Math.max(s.baseScale, Math.min(s.baseScale * 10, s.scale * factor));

      const mx = e.clientX * dpr;
      const my = e.clientY * dpr;
      s.cx = mx - (mx - s.cx) * newScale / s.scale;
      s.cy = my - (my - s.cy) * newScale / s.scale;
      s.scale = newScale;

      draw();
    };

    canvas.addEventListener('wheel', handler, { passive: false });
    return () => canvas.removeEventListener('wheel', handler);
  }, []);

  // Mouse drag
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const dpr = window.devicePixelRatio || 1;

    const onDown = (e: MouseEvent) => {
      const s = stateRef.current;
      s.isDragging = true;
      s.hasDragged = false;
      s.dragStartX = e.clientX * dpr;
      s.dragStartY = e.clientY * dpr;
      s.dragStartCx = s.cx;
      s.dragStartCy = s.cy;
      canvas.style.cursor = 'grabbing';
    };

    const onMove = (e: MouseEvent) => {
      const s = stateRef.current;
      if (!s.isDragging) return;

      const dx = e.clientX * dpr - s.dragStartX;
      const dy = e.clientY * dpr - s.dragStartY;
      if (Math.abs(dx) > 3 * dpr || Math.abs(dy) > 3 * dpr) s.hasDragged = true;

      s.cx = s.dragStartCx + dx;
      s.cy = s.dragStartCy + dy;
      draw();
    };

    const onUp = () => {
      const s = stateRef.current;
      s.isDragging = false;
      canvas.style.cursor = s.scale > s.baseScale * 1.05 ? 'grab' : 'default';
    };

    canvas.addEventListener('mousedown', onDown);
    window.addEventListener('mousemove', onMove);
    window.addEventListener('mouseup', onUp);

    return () => {
      canvas.removeEventListener('mousedown', onDown);
      window.removeEventListener('mousemove', onMove);
      window.removeEventListener('mouseup', onUp);
    };
  }, []);

  // Touch: pinch-to-zoom, drag, double-tap
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const dpr = window.devicePixelRatio || 1;

    const dist = (a: Touch, b: Touch) =>
      Math.hypot(a.clientX - b.clientX, a.clientY - b.clientY);

    const center = (a: Touch, b: Touch) => ({
      x: ((a.clientX + b.clientX) / 2) * dpr,
      y: ((a.clientY + b.clientY) / 2) * dpr,
    });

    const onStart = (e: TouchEvent) => {
      e.preventDefault();
      const s = stateRef.current;

      if (e.touches.length === 1) {
        const now = Date.now();
        if (now - s.lastTapTime < 300) {
          // Double tap
          if (s.scale > s.baseScale * 1.05) {
            resetView();
          } else {
            const mx = e.touches[0].clientX * dpr;
            const my = e.touches[0].clientY * dpr;
            const newScale = s.baseScale * 2.5;
            s.cx = mx - (mx - s.cx) * newScale / s.scale;
            s.cy = my - (my - s.cy) * newScale / s.scale;
            s.scale = newScale;
          }
          draw();
          s.lastTapTime = 0;
          return;
        }
        s.lastTapTime = now;

        s.isDragging = true;
        s.hasDragged = false;
        s.dragStartX = e.touches[0].clientX * dpr;
        s.dragStartY = e.touches[0].clientY * dpr;
        s.dragStartCx = s.cx;
        s.dragStartCy = s.cy;
      } else if (e.touches.length === 2) {
        s.isDragging = false;
        s.lastPinchDist = dist(e.touches[0], e.touches[1]);
      }
    };

    const onMove = (e: TouchEvent) => {
      e.preventDefault();
      const s = stateRef.current;

      if (e.touches.length === 1 && s.isDragging) {
        const dx = e.touches[0].clientX * dpr - s.dragStartX;
        const dy = e.touches[0].clientY * dpr - s.dragStartY;
        if (Math.abs(dx) > 3 * dpr || Math.abs(dy) > 3 * dpr) s.hasDragged = true;

        s.cx = s.dragStartCx + dx;
        s.cy = s.dragStartCy + dy;
        draw();
      } else if (e.touches.length === 2) {
        const d = dist(e.touches[0], e.touches[1]);
        const c = center(e.touches[0], e.touches[1]);

        if (s.lastPinchDist > 0) {
          const factor = d / s.lastPinchDist;
          const newScale = Math.max(
            s.baseScale,
            Math.min(s.baseScale * 10, s.scale * factor)
          );

          s.cx = c.x - (c.x - s.cx) * newScale / s.scale;
          s.cy = c.y - (c.y - s.cy) * newScale / s.scale;
          s.scale = newScale;
        }

        s.lastPinchDist = d;
        draw();
      }
    };

    const onEnd = (e: TouchEvent) => {
      const s = stateRef.current;

      if (e.touches.length === 0) {
        s.isDragging = false;
        s.lastPinchDist = 0;
      } else if (e.touches.length === 1) {
        // Transitioned from pinch to single finger
        s.isDragging = true;
        s.hasDragged = true;
        s.dragStartX = e.touches[0].clientX * dpr;
        s.dragStartY = e.touches[0].clientY * dpr;
        s.dragStartCx = s.cx;
        s.dragStartCy = s.cy;
        s.lastPinchDist = 0;
      }
    };

    canvas.addEventListener('touchstart', onStart, { passive: false });
    canvas.addEventListener('touchmove', onMove, { passive: false });
    canvas.addEventListener('touchend', onEnd);

    return () => {
      canvas.removeEventListener('touchstart', onStart);
      canvas.removeEventListener('touchmove', onMove);
      canvas.removeEventListener('touchend', onEnd);
    };
  }, []);

  // Double-click to toggle zoom
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const dpr = window.devicePixelRatio || 1;

    const handler = (e: MouseEvent) => {
      const s = stateRef.current;
      if (!s.img) return;

      if (s.scale > s.baseScale * 1.05) {
        resetView();
      } else {
        const mx = e.clientX * dpr;
        const my = e.clientY * dpr;
        const newScale = s.baseScale * 2.5;
        s.cx = mx - (mx - s.cx) * newScale / s.scale;
        s.cy = my - (my - s.cy) * newScale / s.scale;
        s.scale = newScale;
      }
      draw();
    };

    canvas.addEventListener('dblclick', handler);
    return () => canvas.removeEventListener('dblclick', handler);
  }, []);

  return (
    <div
      style={{
        position: 'fixed',
        inset: 0,
        zIndex: 9999,
        background: 'rgba(0, 0, 0, 0.92)',
      }}
    >
      {loading && (
        <div
          style={{
            position: 'absolute',
            inset: 0,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            color: 'white',
            fontSize: '1rem',
          }}
        >
          Loading...
        </div>
      )}
      {error && (
        <div
          style={{
            position: 'absolute',
            inset: 0,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            color: 'white',
            fontSize: '1rem',
          }}
        >
          Failed to load image
        </div>
      )}
      <canvas
        ref={canvasRef}
        style={{
          display: 'block',
          touchAction: 'none',
          cursor: 'default',
        }}
      />
      <button
        onClick={onClose}
        style={{
          position: 'absolute',
          top: 16,
          right: 16,
          background: 'rgba(0, 0, 0, 0.5)',
          border: 'none',
          color: 'white',
          fontSize: '1.5rem',
          cursor: 'pointer',
          width: 40,
          height: 40,
          borderRadius: '50%',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          lineHeight: 1,
        }}
        aria-label="Close lightbox"
      >
        &times;
      </button>
    </div>
  );
};

export default Lightbox;

// src/components/photos/Lightbox.svelte
<script lang="ts">
  import { onMount } from 'svelte';

  let { src, onclose }: { src: string; onclose: () => void } = $props();

  let isLoading = $state(true);
  let hasError = $state(false);

  let canvas = $state<HTMLCanvasElement>(undefined!);
  let ctx: CanvasRenderingContext2D;

  const view = {
    img: null as HTMLImageElement | null,
    scale: 1,
    baseScale: 1,
    cx: 0,
    cy: 0,
    isDragging: false,
    dragStartX: 0,
    dragStartY: 0,
    dragStartCx: 0,
    dragStartCy: 0,
    hasDragged: false,
    lastPinchDist: 0,
    lastTapTime: 0
  };

  let prevOverflow = '';

  function draw() {
    if (!view.img || !ctx) return;
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    const w = view.img.naturalWidth * view.scale;
    const h = view.img.naturalHeight * view.scale;
    ctx.drawImage(view.img, view.cx - w / 2, view.cy - h / 2, w, h);
  }

  function resetView() {
    if (!view.img || !canvas) return;
    const padding = 0.9;
    const scaleX = canvas.width / view.img.naturalWidth;
    const scaleY = canvas.height / view.img.naturalHeight;
    view.baseScale = Math.min(scaleX, scaleY) * padding;
    view.scale = view.baseScale;
    view.cx = canvas.width / 2;
    view.cy = canvas.height / 2;
  }

  function sizeCanvas() {
    if (!canvas) return;
    const dpr = window.devicePixelRatio || 1;
    canvas.width = window.innerWidth * dpr;
    canvas.height = window.innerHeight * dpr;
    canvas.style.width = window.innerWidth + 'px';
    canvas.style.height = window.innerHeight + 'px';
    if (view.img) {
      resetView();
      draw();
    }
  }

  onMount(() => {
    prevOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';

    ctx = canvas.getContext('2d')!;
    sizeCanvas();

    const img = new Image();
    img.onload = () => {
      view.img = img;
      isLoading = false;
      resetView();
      draw();
    };
    img.onerror = () => {
      isLoading = false;
      hasError = true;
    };
    img.src = src;

    const onKeydown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onclose();
    };
    const onResize = () => sizeCanvas();

    const onMouseMove = (e: MouseEvent) => {
      if (!view.isDragging) return;
      const dpr = window.devicePixelRatio || 1;
      const dx = e.clientX * dpr - view.dragStartX;
      const dy = e.clientY * dpr - view.dragStartY;
      if (Math.abs(dx) > 3 * dpr || Math.abs(dy) > 3 * dpr) view.hasDragged = true;
      view.cx = view.dragStartCx + dx;
      view.cy = view.dragStartCy + dy;
      draw();
    };
    const onMouseUp = () => {
      view.isDragging = false;
      if (canvas) {
        canvas.style.cursor = view.scale > view.baseScale * 1.05 ? 'grab' : 'default';
      }
    };

    window.addEventListener('keydown', onKeydown);
    window.addEventListener('resize', onResize);
    window.addEventListener('mousemove', onMouseMove);
    window.addEventListener('mouseup', onMouseUp);

    return () => {
      document.body.style.overflow = prevOverflow;
      window.removeEventListener('keydown', onKeydown);
      window.removeEventListener('resize', onResize);
      window.removeEventListener('mousemove', onMouseMove);
      window.removeEventListener('mouseup', onMouseUp);
    };
  });

  // --- Canvas event handlers ---

  function onWheel(e: WheelEvent) {
    e.preventDefault();
    if (!view.img) return;

    const dpr = window.devicePixelRatio || 1;
    const factor = e.deltaY < 0 ? 1.1 : 1 / 1.1;
    const newScale = Math.max(view.baseScale, Math.min(view.baseScale * 10, view.scale * factor));

    const mx = e.clientX * dpr;
    const my = e.clientY * dpr;
    view.cx = mx - ((mx - view.cx) * newScale) / view.scale;
    view.cy = my - ((my - view.cy) * newScale) / view.scale;
    view.scale = newScale;
    draw();
  }

  function onMouseDown(e: MouseEvent) {
    view.isDragging = true;
    view.hasDragged = false;
    const dpr = window.devicePixelRatio || 1;
    view.dragStartX = e.clientX * dpr;
    view.dragStartY = e.clientY * dpr;
    view.dragStartCx = view.cx;
    view.dragStartCy = view.cy;
    canvas.style.cursor = 'grabbing';
  }

  function onDblClick(e: MouseEvent) {
    if (!view.img) return;
    const dpr = window.devicePixelRatio || 1;

    if (view.scale > view.baseScale * 1.05) {
      resetView();
    } else {
      const mx = e.clientX * dpr;
      const my = e.clientY * dpr;
      const newScale = view.baseScale * 2.5;
      view.cx = mx - ((mx - view.cx) * newScale) / view.scale;
      view.cy = my - ((my - view.cy) * newScale) / view.scale;
      view.scale = newScale;
    }
    draw();
  }

  // Touch helpers
  const dist = (a: Touch, b: Touch) => Math.hypot(a.clientX - b.clientX, a.clientY - b.clientY);
  const center = (a: Touch, b: Touch) => {
    const dpr = window.devicePixelRatio || 1;
    return { x: ((a.clientX + b.clientX) / 2) * dpr, y: ((a.clientY + b.clientY) / 2) * dpr };
  };

  function onTouchStart(e: TouchEvent) {
    e.preventDefault();
    const dpr = window.devicePixelRatio || 1;

    if (e.touches.length === 1) {
      const now = Date.now();
      if (now - view.lastTapTime < 300) {
        if (view.scale > view.baseScale * 1.05) {
          resetView();
        } else {
          const mx = e.touches[0].clientX * dpr;
          const my = e.touches[0].clientY * dpr;
          const newScale = view.baseScale * 2.5;
          view.cx = mx - ((mx - view.cx) * newScale) / view.scale;
          view.cy = my - ((my - view.cy) * newScale) / view.scale;
          view.scale = newScale;
        }
        draw();
        view.lastTapTime = 0;
        return;
      }
      view.lastTapTime = now;
      view.isDragging = true;
      view.hasDragged = false;
      view.dragStartX = e.touches[0].clientX * dpr;
      view.dragStartY = e.touches[0].clientY * dpr;
      view.dragStartCx = view.cx;
      view.dragStartCy = view.cy;
    } else if (e.touches.length === 2) {
      view.isDragging = false;
      view.lastPinchDist = dist(e.touches[0], e.touches[1]);
    }
  }

  function onTouchMove(e: TouchEvent) {
    e.preventDefault();
    const dpr = window.devicePixelRatio || 1;

    if (e.touches.length === 1 && view.isDragging) {
      const dx = e.touches[0].clientX * dpr - view.dragStartX;
      const dy = e.touches[0].clientY * dpr - view.dragStartY;
      if (Math.abs(dx) > 3 * dpr || Math.abs(dy) > 3 * dpr) view.hasDragged = true;
      view.cx = view.dragStartCx + dx;
      view.cy = view.dragStartCy + dy;
      draw();
    } else if (e.touches.length === 2) {
      const d = dist(e.touches[0], e.touches[1]);
      const c = center(e.touches[0], e.touches[1]);

      if (view.lastPinchDist > 0) {
        const factor = d / view.lastPinchDist;
        const newScale = Math.max(
          view.baseScale,
          Math.min(view.baseScale * 10, view.scale * factor)
        );
        view.cx = c.x - ((c.x - view.cx) * newScale) / view.scale;
        view.cy = c.y - ((c.y - view.cy) * newScale) / view.scale;
        view.scale = newScale;
      }
      view.lastPinchDist = d;
      draw();
    }
  }

  function onTouchEnd(e: TouchEvent) {
    if (e.touches.length === 0) {
      view.isDragging = false;
      view.lastPinchDist = 0;
    } else if (e.touches.length === 1) {
      const dpr = window.devicePixelRatio || 1;
      view.isDragging = true;
      view.hasDragged = true;
      view.dragStartX = e.touches[0].clientX * dpr;
      view.dragStartY = e.touches[0].clientY * dpr;
      view.dragStartCx = view.cx;
      view.dragStartCy = view.cy;
      view.lastPinchDist = 0;
    }
  }
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<div class="lightbox">
  <canvas
    bind:this={canvas}
    style="display:block; touch-action:none; cursor:default;"
    onwheel={onWheel}
    onmousedown={onMouseDown}
    ondblclick={onDblClick}
    ontouchstart={onTouchStart}
    ontouchmove={onTouchMove}
    ontouchend={onTouchEnd}
  ></canvas>

  {#if isLoading}
    <div class="lightbox-status">Loading...</div>
  {/if}

  {#if hasError}
    <div class="lightbox-status">Failed to load image</div>
  {/if}

  <button class="lightbox-close" aria-label="Close lightbox" onclick={() => onclose()}
    >&times;</button
  >
</div>

<style>
  .lightbox {
    position: fixed;
    inset: 0;
    z-index: 9999;
    background: rgba(0, 0, 0, 0.92);
  }

  .lightbox-status {
    position: absolute;
    inset: 0;
    display: flex;
    align-items: center;
    justify-content: center;
    color: white;
    font-size: 1rem;
    pointer-events: none;
  }

  .lightbox-close {
    position: absolute;
    top: 1rem;
    right: 1rem;
    background: rgba(0, 0, 0, 0.5);
    border: none;
    color: white;
    font-size: 1.5rem;
    cursor: pointer;
    width: 2.5rem;
    height: 2.5rem;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    line-height: 1;
  }
</style>
